---
dependencies: []
galaxy_info:
  author: Julien Girardin
  description: Make groups of master and nodes
  company: Enix
  license: Apache
  min_ansible_version: 2.7
  platforms:
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04
  galaxy_tags:
    - kubernetes
