---
- name: 'Find kube_apiserver_advertise_address'
  import_tasks: find_ip.yml
  when:
    - _control_plane|bool
  vars:
    found_address_var: "_kube_apiserver_advertise_address"
    network_cidr: "{{ kube_apiserver_advertise_cidr|default(kube_control_plane_cidr, true) }}"

- name: 'Find etcd_metrics_bind_address'
  import_tasks: find_ip.yml
  when:
    - _control_plane|bool
  vars:
    found_address_var: "_etcd_metrics_bind_address"
    network_cidr: "{{ etcd_metrics_bind_cidr|default(kube_control_plane_cidr, true) }}"

- name: 'Find kube_controller_manager_bind_address'
  import_tasks: find_ip.yml
  when:
    - _control_plane|bool
  vars:
    found_address_var: "_kube_controller_manager_bind_address"
    network_cidr: "{{ kube_controller_manager_bind_cidr|default(kube_control_plane_cidr, true) }}"

- name: 'Find kube_scheduler_bind_address'
  import_tasks: find_ip.yml
  when:
    - _control_plane|bool
  vars:
    found_address_var: "_kube_scheduler_bind_address"
    network_cidr: "{{ kube_scheduler_bind_cidr|default(kube_control_plane_cidr, true) }}"

- name: 'Find kubelet_node_ip'
  import_tasks: find_ip.yml
  when:
    - not _skip_node_ip|bool
  vars:
    found_address_var: "_kubelet_node_ip"
    network_cidr: "{{ kubelet_node_ip_cidr }}"
