---
- name: "Compute init-config"
  set_fact:
    _init_config: '{{ lookup("template", role_path ~ "/templates/init_config.j2") | from_yaml }}'

- name: "Write kubeadm config"
  import_role:
    name: kubeadm_configs_update
  vars:
    init_config: '{{ _init_config }}'

- name: 'Kubeadm init control init'
  command: >-
    kubeadm init --config {{ kubeadm_config_yaml }}
    {% if enable_kubeadm_patches -%}
      {% if target_kube_version is version("1.22", ">=") -%}
      --patches
      {%- else -%}
      --experimental-patches
      {%- endif %}
      {{ kubeadm_patch_dir }}
    {% endif %}
