---
- name: 'Get version of kubeadm package'
  package_facts:

- name: 'Display information about all packages'
  debug:
    var: packages
    verbosity: 1

# Look at the current version of kubernetes (ex: 1.17.8)
# Then look at possible version of kubeadm that match this version (ex: 1.17.8-01)
# Retain the kubeadm version if match found, fallback on kubernetes otherwise
# Last fallback is the default version, if no cluster running
- name: 'Export variable for other hosts'
  set_fact:
    target_kube_version: '{{ _kube_version }}'
    target_kubeadm_version: '{{ _kubeadm_version }}'
  vars:
    _kube_version: >-
      {%- if current_cp_version -%}
        {%- if current_cp_version|regex_search(kube_version ~ '.*') or not kube_version -%}
           {{ current_cp_version }}
        {%- else -%}
           {{ kube_version|default(default_kube_version, true) }}
        {%- endif -%}
      {%- else -%}
        {{ kube_version|default(default_kube_version, true) }}
      {%- endif -%}
    _kubeadm_version: >-
      {%- set kubeadm_match = ansible_play_hosts
           |map('extract', hostvars, ['packages', 'kubeadm', 0, 'version'])
           |map('default')|select('match', _kube_version ~ '.*')|list -%}
      {%- if kubeadm_match|length > 0 -%}
        {{ kubeadm_match|first }}
      {%- else -%}
        {{ _kube_version }}
      {%- endif -%}

- name: 'Display wanted version of kuberbenetes'
  debug:
    var: target_kube_version

- name: 'Display wanted version of kubeadm'
  debug:
    var: target_kubeadm_version

- name: 'Check that version upgrade is one step'
  fail:
    msg: 'Version upgrade is not allowed: {{ current_cp_version }} => {{ target_kube_version }}'
  when:
    - current_cp_version|length > 0
    - (current_major != target_major) or (current_minor|int - target_minor|int)|abs > 1
  vars:
    current_version_split: '{{ (current_cp_version|regex_findall("(?:\d+)"))[0:2] }}'
    current_major: '{{ current_version_split|first }}'
    current_minor: '{{ current_version_split|last }}'
    target_version_split: '{{ (target_kube_version|regex_findall("(?:\d+)"))[0:2] }}'
    target_major: '{{ target_version_split|first }}'
    target_minor: '{{ target_version_split|last }}'

- name: 'Add control_plan to cp_init, if no cluster found'
  add_host:
    name: '{{ ansible_play_hosts|first }}'
    group: cp_init
  changed_when: false
  check_mode: false
  run_once: true
  when:
    - groups.cp_running|default([])|length == 0

- name: 'Add control_plane to cp_upgrade, if upgrade needed'
  add_host:
    name: '{{ (groups.cp_running|default([0], true))|first }}'
    group: cp_upgrade
  changed_when: false
  check_mode: false
  run_once: true
  when:
    - current_cp_version|length > 0
    - not(current_cp_version|regex_search(target_kube_version ~ '.*'))
