---
default_kubeadm_config:
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration

default_kubelet_config:
  apiVersion: kubelet.config.k8s.io/v1beta1
  kind: KubeletConfiguration

default_kubeproxy_config:
  apiVersion: kubeproxy.config.k8s.io/v1alpha1
  kind: KubeProxyConfiguration
