---
enable_kubeadm_patches: true
kubeadm_patch_dir: /etc/kubernetes/patches
kube_cp_group: kube_control_plane
kube_worker_group: kube_workers

cp_node: '{{ (groups.cp_running|default(groups[kube_cp_group]))|first }}'
