---
- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  roles:
    - role: find_ip
      vars:
        _control_plane: true
    - role: kubeadm_configs_compute
    - role: preflight_check_cp

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}:{{ kube_worker_group|default("kube_workers") }}'
  roles:
    - role: find_ip
    - role: preflight_check_nodes

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  roles:
    - role: control_plane_patches

- hosts: cp_init
  gather_facts: false
  vars:
    _control_plane: true
  roles:
    - role: packages
    - role: init_cp

- hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  roles:
    - role: bootstrap_token
    - role: kubeadm_configs_update

# This has to be overly cautious on package upgade
- hosts: cp_upgrade
  gather_facts: false
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_cp
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true

# Upgrade conrol-plane nodes
- name: 'Upgrade to control plane nodes'
  hosts: '{{ kube_cp_group|default("kube_control_plane") }}:&nodes_upgrade'
  serial: '{{ upgrade_cp_serial|default(1) }}'
  gather_facts: false
  vars:
    _control_plane: true
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_nodes
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true

# Upgrade worker nodes
- name: 'Upgrade to workers nodes'
  hosts: '{{ kube_worker_group|default("kube_workers") }}:&nodes_upgrade'
  serial: '{{ upgrade_worker_serial|default(1) }}'
  gather_facts: false
  roles:
    - role: packages
      vars:
        kubeadm_pkgs: true
        node_pkgs: false
    - role: upgrade_nodes
    - role: packages
      vars:
        kubeadm_pkgs: false
        node_pkgs: true

# Join control-plane nodes
- name: 'Join new control plane nodes'
  hosts: '{{ kube_cp_group|default("kube_control_plane") }}'
  gather_facts: false
  vars:
    _control_plane: true
  roles:
    - role: find_ip
    - role: packages
    - role: control_plane_patches
    - role: join_nodes
    - role: user_kubeconfig

# Join worker nodes
- name: 'Join new workers nodes'
  hosts: '{{ kube_worker_group|default("kube_workers") }}'
  gather_facts: false
  roles:
    - role: find_ip
    - role: packages
    - role: join_nodes
